const Joi = require('joi');
const { CaseInsensitiveSchema } = require('../schema');

const constraints = require('./_constraints');

/**
 * Used to download monthly or daily statement files generated by the Barion system.
 *
 * Note: Username/Password authentication has been deprecated by Barion.
 * Only API key authentication is supported.
 *
 * @see {@link https://docs.barion.com/Statement-Download-v2|Barion API Documentation}
 */
const schema = Joi.object({
    ApiKey: Joi.string().required()
        .pattern(/^[0-9a-fA-F]{32}$/),
    Year: Joi.number().required()
        .greater(1969),
    Month: Joi.number().required()
        .min(1)
        .max(12),
    Day: Joi.number().optional()
        .min(1)
        .max(31),
    Currency: Joi.string().required()
        .valid(...constraints.Currency)
});

module.exports = new CaseInsensitiveSchema(schema);
