const Joi = require('joi');
const { CaseInsensitiveSchema } = require('../schema');

const constraints = require('./_constraints');

/**
 * Used to download monthly or daily statement files generated by the Barion system.
 *
 * @see {@link https://docs.barion.com/Statement-Download-v2|Barion API Documentation}
 */
const schema = Joi.object({
    UserName: Joi.string().optional()
        .email(),
    Password: Joi.string().optional(),
    ApiKey: Joi.string().optional(),
    Year: Joi.number().required()
        .greater(1969),
    Month: Joi.number().required()
        .min(1)
        .max(12),
    Day: Joi.number().optional()
        .min(1)
        .max(31),
    Currency: Joi.string().required()
        .valid(...constraints.Currency)
}).or('UserName', 'ApiKey')
    .with('UserName', 'Password');

module.exports = new CaseInsensitiveSchema(schema);
