const { URL } = require('url');
const { getFromBarion, getBinaryFromBarion, postToBarion } = require('./fetch-api');
const { baseUrls, endPoints } = require('./constants');

/**
 * Returns the base URL based on environment setting.
 * @param {String} environment - The environment to use ('prod' or 'test').
 */
function getBaseUrl(environment) {
    if (!environment || typeof environment !== 'string') {
        return baseUrls.test;
    }

    return baseUrls[environment];
}

/**
 * Sends the request to Barion API based on given information.
 * @param {String} environment - The environment to use ('prod' or 'test').
 * @param {Object} endpoint - The endpoint to use (at least with 'method' and 'path' fields).
 * @param {Object} options - The request object to send.
 */
function doRequest(environment, endpoint, options) {
    const { method, path } = endpoint;
    const url = new URL(getBaseUrl(environment));

    url.pathname = path;

    if (endpoint.binary) {
        return getBinaryFromBarion(url, options);
    }

    switch (method) {
        case 'GET':
            return getFromBarion(url, options);
        case 'POST':
            return postToBarion(url, options);
        default:
            throw new Error(`Not supported HTTP method: ${method}`);
    }
}

/**
 * Starts a new payment in Barion.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function startPayment(environment, options) {
    return doRequest(environment, endPoints.startPayment, options);
}

/**
 * Gets the state of a payment from Barion.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function getPaymentState(environment, options) {
    return doRequest(environment, endPoints.getPaymentState, options);
}

/**
 * Finalizes a pending reservation in the Barion system.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function finishReservation(environment, options) {
    return doRequest(environment, endPoints.finishReservation, options);
}

/**
 * Captures a previously authorized delayed capture payment.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function captureAuthorizedPayment(environment, options) {
    return doRequest(environment, endPoints.captureAuthorizedPayment, options);
}

/**
 * Cancels a previously authorized delayed capture payment.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function cancelAuthorizedPayment(environment, options) {
    return doRequest(environment, endPoints.cancelAuthorizedPayment, options);
}

/**
 * Completes a formerly prepared and 3DS authenticated payment. 
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function completePayment(environment, options) {
    return doRequest(environment, endPoints.completePayment, options);
}

/**
 * Refunds a payment in Barion.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function refundPayment(environment, options) {
    return doRequest(environment, endPoints.refundPayment, options);
}

/**
 * Sends money out of the Barion system via bank transfer.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function bankTransfer(environment, options) {
    return doRequest(environment, endPoints.bankTransfer, options);
}

/**
 * Queries the existing accounts of the calling user.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function getAccounts(environment, options) {
    return doRequest(environment, endPoints.getAccounts, options);
}

/**
 * Sends money to an email address.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function emailTransfer(environment, options) {
    return doRequest(environment, endPoints.emailTransfer, options);
}

/**
 * Download monthly or daily statement files generated by the Barion system.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function downloadStatement(environment, options) {
    return doRequest(environment, endPoints.downloadStatement, options);
}

/**
 * Make a payment using Google Pay token.
 * @param {String} environment - The environment to use ('test' or 'prod').
 * @param {Object} options - The final request body to send to the Barion API.
 */
function startPaymentWithGoogleToken(environment, options) {
    return doRequest(environment, endPoints.startPaymentWithGoogleToken, options);
}

module.exports = {
    startPayment,
    getPaymentState,
    finishReservation,
    refundPayment,
    captureAuthorizedPayment,
    cancelAuthorizedPayment,
    completePayment,
    bankTransfer,
    getAccounts,
    emailTransfer,
    downloadStatement,
    startPaymentWithGoogleToken,
    _private: {
        getBaseUrl,
        doRequest
    }
};
